populate pyproject.toml
swift-nav/piksi_tools pull request #1281
Opened 2023-06-08 16:33 UTC by achubbic-snav

2023-06-08 20:32 UTC, denisng commented on pyproject.toml
> +futures = "3.1.1"
@silverjam, now that we have dropped support for Python 2, do we still need these backports?

Not critical to do in this change. I can open a ticket if we want to punt for now.

2023-06-08 20:32 UTC, denisng commented on pyproject.toml
> +six = "1.13.0"
@silverjam, ditto, dropping Python 2, do we still need this compatibility stuff

2023-06-08 20:32 UTC, denisng commented on pyproject.toml
>  [tool.poetry.dependencies]
@silverjam, would having requirements defined here conflict with `setup.cfg`?

2023-06-08 22:41 UTC, silverjam approved these changes
This repo isn't using poetry for building it's wheel, sorry for the confusion around that.  We should just drop the `poetry` sections from the pyproject.toml.

2023-06-08 22:42 UTC, silverjam requested changes
This repo isn't using poetry for building it's wheel, sorry for the confusion around that. We should just drop the poetry sections from the pyproject.toml.

2023-06-08 22:47 UTC, silverjam commented
@achubbic-snav please see https://github.com/swift-nav/piksi_tools/pull/1282

2023-06-12 18:24 UTC, silverjam commented
Close?

2023-06-13 19:39 UTC, closed without merging